name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: sms-terminal
            asset_name: sms-terminal-linux-x64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: sms-terminal
            asset_name: sms-terminal-linux-aarch64
          - target: i686-pc-windows-gnu
            os: ubuntu-latest
            artifact_name: sms-terminal.exe
            asset_name: sms-terminal-windows-x32
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            artifact_name: sms-terminal.exe
            asset_name: sms-terminal-windows-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation dependencies (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install cross-compilation dependencies (Windows)
        if: contains(matrix.target, 'windows')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64

      - name: Configure cross-compilation
        run: |
          mkdir -p .cargo
          cat >> .cargo/config.toml << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          
          [target.i686-pc-windows-gnu]
          linker = "i686-w64-mingw32-gcc"
          ar = "i686-w64-mingw32-ar"
          
          [target.x86_64-pc-windows-gnu]
          linker = "x86_64-w64-mingw32-gcc"
          ar = "x86_64-w64-mingw32-ar"
          EOF

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Linux)
        if: runner.os == 'Linux' && !contains(matrix.target, 'windows')
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            aarch64-linux-gnu-strip target/${{ matrix.target }}/release/sms-terminal
          else
            strip target/${{ matrix.target }}/release/sms-terminal
          fi

      - name: Strip binary (Windows)
        if: contains(matrix.target, 'windows')
        run: |
          if [[ "${{ matrix.target }}" == "i686-pc-windows-gnu" ]]; then
            i686-w64-mingw32-strip target/${{ matrix.target }}/release/sms-terminal.exe
          else
            x86_64-w64-mingw32-strip target/${{ matrix.target }}/release/sms-terminal.exe
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed
            
            Automated release for version ${{ github.ref_name }}
            
            ### Downloads
            - **Linux x64**: sms-terminal-linux-x64
            - **Linux ARM64**: sms-terminal-linux-aarch64
            - **Windows x32**: sms-terminal-windows-x32.exe
            - **Windows x64**: sms-terminal-windows-x64.exe

      - name: Upload Linux x64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/sms-terminal-linux-x64/sms-terminal
          asset_name: sms-terminal-linux-x64
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/sms-terminal-linux-aarch64/sms-terminal
          asset_name: sms-terminal-linux-aarch64
          asset_content_type: application/octet-stream

      - name: Upload Windows x32 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/sms-terminal-windows-x32/sms-terminal.exe
          asset_name: sms-terminal-windows-x32.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows x64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/sms-terminal-windows-x64/sms-terminal.exe
          asset_name: sms-terminal-windows-x64.exe
          asset_content_type: application/octet-stream